---
abstract: 'parallel benchmark module'
author:
  - 'FUJIWARA Shunichiro <fujiwara@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.2, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parallel-Benchmark
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Parallel::Benchmark:
    file: lib/Parallel/Benchmark.pm
    version: 0.08
requires:
  File::Temp: 0
  Log::Minimal: 0
  Mouse: 0
  POSIX: 0
  Parallel::ForkManager: v0.7.6
  Parallel::Scoreboard: 0
  Time::HiRes: 0
  Try::Tiny: 0
resources:
  bugtracker: https://github.com/fujiwara/p5-Parallel-Benchmark/issues
  homepage: https://github.com/fujiwara/p5-Parallel-Benchmark
  repository: git://github.com/fujiwara/p5-Parallel-Benchmark.git
version: 0.08
x_contributors:
  - 'FUJIWARA Shunichiro <fujiwara.shunichiro@gmail.com>'
